spring:
  application.name: greeting
  # ===============================
  # = DATA SOURCE
  # ===============================
  # Set here configurations for the database connection
  # all hikari properties https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximum-pool-size: 50
      allow-pool-suspension: true
    url: jdbc:postgresql://localhost:5432/statistic
    username: postgres
    password: postgres@123
  driver-class-name: org.postgresql.Driver
  testOnBorrow: true
  testWhileIdle: true # Keep the connection alive if idle for a long time (needed in production)
  validationQuery: SELECT 1

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  # Show or not log for each sql query
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect # Allows Hibernate to generate SQL optimized for a particular DBMS
        generate_statistics: true #Turn Statistics on
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl # Naming strategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # Naming strategy


logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    root: info
    org.hibernate:
      stat: debug #Turn Statistics on
      type: trace # Show all queries

